name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: Get the code
        uses: actions/checkout@v4
        with: 
          ref: main
          fetch-depth: 0
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci 
      - name: Run tests
        run: npm test
